### ISSUE TITLE
Gameboy Color emulator app?

### ISSUE THREAD

**Issue by EternityForest** [radio3-network/BluemchenGUI#2]
Seems like it wouldn't be too hard to port something like this, it would just require changing the license to GPL: https://github.com/badgeteam/mch2022-esp32-app-gnuboy

Adding that would give access to a large library of content, plus GB Studio for creating games without coding, that are not limited to just one platform.

It looks pretty easy to use GB Studio plugins to and extend GNUBoy, and allow extra features like touch input and Bluetooth in homebrew games and apps.

**Comment by maxbrito500** [comment]
Indeed. On this model was not anticipated to use buttons nor play emulated games.

Unfortunately don't have the time to help you with an implementation but would certainly be a cool feature.
